### PR TITLE
fix for Firefox

### PR DESCRIPTION
**Pull request by MikkCZ**
Hi @w-vi.

I have made few adjustments to make the extension work in Firefox too. I have tested in latest Chromium and works there fine too. If you want to publish to AMO too, please read [Publishing your extension](https://developer.mozilla.org/Add-ons/WebExtensions/Publishing_your_WebExtension) and [manifest.json](https://developer.mozilla.org/Add-ons/WebExtensions/manifest.json) how to do it and what are the differences between Chrome and Firefox extensions. Btw. there is a handy tool called [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) too. ;)

Please let me know if there is anything more I can help you with.

### CODE REVIEW

**Comment by w-vi** [comment]
Cool, I actually wanted to do it myself as I migrated to Firefox. Thanks for saving me time. I'll publish it on AMO as well.

**Comment by MikkCZ** [comment]
Let me know, once the add-on is approved. I will add it to [our collection](https://addons.mozilla.org/cs/firefox/collections/mozillacz/prekladace-webovych-stranek/).

**Comment by w-vi** [comment]
@MikkCZ https://addons.mozilla.org/en-US/firefox/addon/prelozit-pomoci-slovnik-cz/

**Comment by MikkCZ** [comment]
It's [here](https://addons.mozilla.org/cs/firefox/collections/mozillacz/prekladace-webovych-stranek/) and [there](https://addons.mozilla.org/cs/firefox/collections/mozillacz/ceske-vyhledavaci-moduly/). :)

**Pull request merged**
